# Generated by Django 5.1.4 on 2025-02-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
    ]
